  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test07/../../riesenia/ZacharMarek/mboxer/mboxer.py", line 37
    stav_popis = "ok"
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test07/test.py", line 164, in <module>
    s.connect(('localhost',9999))
ConnectionRefusedError: [Errno 111] Connection refused
