Traceback (most recent call last):
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test10/../../riesenia/Ajurecekova/mboxer/mail.py", line 126, in <module>
    request=f.readline().decode('UTF-8')
ValueError: peek of closed file
Traceback (most recent call last):
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test10/test.py", line 189, in <module>
    response_real=ResponseFromSocket(f)
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test10/test.py", line 99, in __init__
    status_in=readline_tee(f)
  File "/home/gejza/vyuka/l2021/ps/zadanie1/tests/test10/test.py", line 37, in readline_tee
    line=f.readline().decode('utf-8')
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
